### ISSUE TITLE
Debugging latest experiments

### ISSUE THREAD

**Issue by bas-rustenburg** [choderalab/host-guest#14]
0.516635282602 millimole / liter  is the concentration of the host stock solution according to my script.

I'm going to check whether that is a calculation error, or a notation error on my part. I was expecting to make a ~ 1 mM stock..

**Comment by bas-rustenburg** [comment]
It was a calculation error when I prepared the solutions. I will remake the stock solution before next experiment.

This explains why every experiment had the same syringe concentration. To get the best Rm, things were just maxed out. Will still check for any further bugs.

**Comment by bas-rustenburg** [comment]
Oh, FWIW, the guest stock solutions were all approximately 1 mM, as desired.

**Comment by jchodera** [comment]
Aha!  Thanks for tracking this down---that explains a lot!

**Comment by bas-rustenburg** [comment]
Found my error in the original calculation. Instead of dividing by the purity, I multiplied by it..

(host.molecular_weight * host.purity * Quantity('1 millimole / liter') * Quantity('10 milliliter')).to('milligram')

Which gives about 8 mg instead of the required 16mg.

**Comment by bas-rustenburg** [comment]
New solution was made. Problem solved.
